apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myweb-rs
spec:
    replicas: 3
    selector: 
        matchLabels:
            env: production
    template:
        metadata: 
            name: mywebpod
            labels:
                env: production
        spec:
            containers:
            -    name: mywebcon
                 image: httpd